import test from 'node:test';
import assert from 'node:assert/strict';
import worker from '../worker/index.js';
import {createDatabase} from '../scripts/database.mjs';
const cookie='rml_session=11111111-1111-4111-8111-111111111111';
function setup(t){const DB=createDatabase();t.after(()=>DB.close());const env={DB,ADMIN_TOKEN:'test-admin-secret'};return async(path,payload,options={})=>{const response=await worker.fetch(new Request('https://test.local'+path,{method:payload===undefined?'GET':'POST',headers:{cookie,'Content-Type':'application/json',origin:'https://test.local',...options.headers},...(payload===undefined?{}:{body:JSON.stringify(payload)})}),env);return{status:response.status,data:await response.json(),headers:response.headers};};}
const review={landlordId:'demo-maple',maintenance:5,communication:4,deposit:3,again:true,year:2025,title:'一次完整的租住体验',body:'这是用于测试的租住体验，维修沟通及时，退租交接顺利，费用说明比较清楚。',consent:true};
const unit={address:'100 Test Avenue',city:'Toronto',latitude:43.65,longitude:-79.38,unit:'1205',rentalChannel:'direct',consent:true};
test('demo scores are derived from sample reviews',async t=>{const call=setup(t);const r=await call('/api/landlords/demo-maple');assert.equal(r.status,200);assert.equal(r.data.landlord.count,2);assert.equal(r.data.landlord.score,28/6);assert.equal(r.data.landlord.again,100);assert.equal(r.data.landlord.demo,true);assert.ok(!JSON.stringify(r.data).includes('session'));});
test('review is durable in database, pending until authorized moderation, duplicate rejected',async t=>{const call=setup(t);const r=await call('/api/reviews',review);assert.equal(r.status,201);assert.equal(r.data.status,'pending');assert.equal((await call('/api/landlords/demo-maple')).data.landlord.count,2);assert.equal((await call('/api/reviews',review)).status,409);assert.equal((await call('/api/admin/moderate',{id:r.data.id,status:'published'})).status,403);assert.equal((await call('/api/admin/moderate',{id:r.data.id,status:'published'},{headers:{authorization:'Bearer test-admin-secret'}})).status,200);const detail=(await call('/api/landlords/demo-maple')).data;assert.equal(detail.landlord.count,3);assert.equal(detail.myReviewStatus,'published');assert.ok(!('session' in detail.reviews[0]));});
test('invalid rating, foreign origin and malformed payload are rejected',async t=>{const call=setup(t);assert.equal((await call('/api/reviews',{...review,deposit:6})).status,400);assert.equal((await call('/api/reviews',review,{headers:{origin:'https://other.example'}})).status,403);assert.equal((await call('/api/reviews',null)).status,400);assert.equal((await call('/api/reviews',{...review,landlordId:'not-found'})).status,404);assert.equal((await call('/api/reviews',{...review,body:'short'})).status,400);});
test('building and exact Unit resolve to separate landlords',async t=>{const call=setup(t);const first=await call('/api/listings',unit);assert.equal(first.status,201);const second=await call('/api/listings',{...unit,buildingId:first.data.buildingId,unit:'1206',rentalChannel:'agent'});assert.equal(second.status,201);assert.notEqual(first.data.landlordId,second.data.landlordId);const a=await call(`/api/buildings/${first.data.buildingId}?unit=1205`);assert.equal(a.data.listings.length,1);assert.equal(a.data.listings[0].rental_channel,'direct');assert.equal((await call(`/api/buildings/${first.data.buildingId}?unit=1206`)).data.listings[0].rental_channel,'agent');const b=await call(`/api/buildings/${first.data.buildingId}?unit=12`);assert.equal(b.data.listings.length,0);const all=await call('/api/buildings');assert.equal(all.data.buildings.length,1);assert.equal(all.data.buildings[0].units,2);});
test('same Unit in another building is distinct and normalized duplicates roll back',async t=>{const call=setup(t);const a=await call('/api/listings',unit);assert.equal((await call('/api/listings',{...unit,unit:'Unit 1205',rentalChannel:'agent'})).status,409);const b=await call('/api/listings',{...unit,address:'200 Test Avenue'});assert.equal(b.status,201);assert.notEqual(a.data.buildingId,b.data.buildingId);const list=await call('/api/landlords');assert.equal(list.data.landlords.filter(l=>!l.demo).length,2);});
test('Unit review is associated with the right landlord and does not leak to another Unit',async t=>{const call=setup(t);const a=(await call('/api/listings',unit)).data;const b=(await call('/api/listings',{...unit,buildingId:a.buildingId,unit:'1206'})).data;assert.notEqual(a.landlordId,b.landlordId);const r=(await call('/api/reviews',{...review,landlordId:a.landlordId,listingId:a.id}));assert.equal(r.status,201);await call('/api/admin/moderate',{id:r.data.id,status:'published'},{headers:{authorization:'Bearer test-admin-secret'}});const detail=await call(`/api/landlords/${a.landlordId}?listing=${a.id}`);assert.equal(detail.data.context.unit,'1205');assert.equal(detail.data.landlord.count,1);assert.equal((await call(`/api/landlords/${b.landlordId}?listing=${b.id}`)).data.landlord.count,0);assert.equal((await call('/api/reviews',{...review,landlordId:b.landlordId,listingId:b.id})).status,201);assert.equal((await call('/api/reviews',{...review,listingId:a.id})).status,400);});
test('report is stored once and never reveals the reporting session',async t=>{const call=setup(t);const report={reviewId:'sample-1',reason:'测试举报：内容需要核实'};assert.equal((await call('/api/reports',report)).status,201);assert.equal((await call('/api/reports',report)).status,409);assert.equal((await call('/api/admin/queue')).status,403);const queue=await call('/api/admin/queue',undefined,{headers:{authorization:'Bearer test-admin-secret'}});assert.equal(queue.data.reports.length,1);assert.ok(!JSON.stringify(queue.data).includes('session'));});
test('invalid building coordinates and missing consent are rejected',async t=>{const call=setup(t);assert.equal((await call('/api/listings',{...unit,latitude:200})).status,400);assert.equal((await call('/api/listings',{...unit,consent:false})).status,400);assert.equal((await call('/api/listings',{...unit,unit:'Unit '})).status,400);});
test('missing database returns an explicit unavailable state',async()=>{const response=await worker.fetch(new Request('https://test.local/api/buildings'),{});assert.equal(response.status,503);assert.ok((await response.json()).error.includes('数据库'));});

test('rental channel is required and constrained',async t=>{const call=setup(t);for(const rentalChannel of [undefined,'unknown','other',''])assert.equal((await call('/api/listings',{...unit,rentalChannel})).status,400);});
