import {readFile,mkdir,writeFile,cp} from 'node:fs/promises';
const root=new URL('../',import.meta.url);
const assets={};
for(const [file,type] of [['index.html','text/html; charset=utf-8'],['app.js','text/javascript; charset=utf-8'],['map.js','text/javascript; charset=utf-8'],['catalogue.js','text/javascript; charset=utf-8'],['buildings.json','application/json; charset=utf-8'],['map.css','text/css; charset=utf-8'],['vendor/leaflet.js','text/javascript; charset=utf-8'],['vendor/leaflet.css','text/css; charset=utf-8'],['style.css','text/css; charset=utf-8'],['favicon.svg','image/svg+xml'],['admin.html','text/html; charset=utf-8'],['admin.js','text/javascript; charset=utf-8']])assets['/'+file]={body:await readFile(new URL('public/'+file,root),'utf8'),type};
const data=(await readFile(new URL('src/data.js',root),'utf8')).replaceAll('export const ','const ');
const properties=(await readFile(new URL('src/properties.js',root),'utf8')).replace('export async function','async function');
const source=(await readFile(new URL('worker/index.js',root),'utf8')).replace("import { demoLandlords, demoReviews } from '../src/data.js';",()=>data).replace("import { propertyRoutes } from '../src/properties.js';",()=>properties).replace('/*__ASSETS__*/ {}',()=>JSON.stringify(assets));
await mkdir(new URL('dist/server/',root),{recursive:true});await mkdir(new URL('dist/.openai/',root),{recursive:true});
await writeFile(new URL('dist/server/index.js',root),source);await cp(new URL('.openai/hosting.json',root),new URL('dist/.openai/hosting.json',root));await cp(new URL('drizzle/',root),new URL('dist/.openai/drizzle/',root),{recursive:true});
console.log('Built Worker with embedded assets and database migrations.');
