import { demoLandlords, demoReviews } from '../src/data.js';
import { propertyRoutes } from '../src/properties.js';
const assets = /*__ASSETS__*/ {};
const security={'X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://tile.openstreetmap.org; connect-src 'self' https://photon.komoot.io; frame-ancestors 'none'; base-uri 'none'; form-action 'self'",'Permissions-Policy':'camera=(), microphone=(), geolocation=(self)'};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{...security,'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}});
class HttpError extends Error{constructor(status,message){super(message);this.status=status;}}
function database(env){if(!env.DB)throw new HttpError(503,'数据库暂时不可用，请稍后重试。');return env.DB;}
async function rows(db,sql,...args){return(await db.prepare(sql).bind(...args).all()).results;}
function text(value,min,max,label){if(typeof value!=='string'||value.trim().length<min||value.trim().length>max)throw new HttpError(400,`${label}需要 ${min}–${max} 个字符。`);return value.trim();}
const publicReview=r=>{const{session,scope,...review}=r;return review;};
async function allLandlords(db){const landlords=await rows(db,'SELECT id,name,city,district FROM landlords ORDER BY created_at DESC'),listings=await rows(db,'SELECT l.id,l.landlord_id,l.unit,l.rental_channel,b.address,b.city FROM listings l JOIN buildings b ON b.id=l.building_id ORDER BY b.address,l.unit');return[...demoLandlords,...landlords.map(l=>({...l,listings:listings.filter(x=>x.landlord_id===l.id)}))];}
async function publicReviews(db){return[...demoReviews,...await rows(db,"SELECT r.id,r.landlord_id,r.listing_id,r.maintenance,r.communication,r.deposit,r.again,r.title,r.body,r.year,r.created_at,r.status,l.unit,b.address,b.city FROM reviews r LEFT JOIN listings l ON l.id=r.listing_id LEFT JOIN buildings b ON b.id=l.building_id WHERE r.status = 'published'")];}
function summarize(landlord,reviews){const list=reviews.filter(r=>r.landlord_id===landlord.id),n=list.length,avg=key=>n?list.reduce((s,r)=>s+r[key],0)/n:null;return{...landlord,count:n,score:n?(avg('maintenance')+avg('communication')+avg('deposit'))/3:null,maintenance:avg('maintenance'),communication:avg('communication'),deposit:avg('deposit'),again:n?Math.round(avg('again')*100):null};}
async function identity(request){const cookie=request.headers.get('cookie')||'';let id=cookie.match(/(?:^|;\s*)rml_session=([a-f0-9-]{36})(?:;|$)/)?.[1];const fresh=!id;id||=crypto.randomUUID();const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(id));return{id,fresh,hash:Array.from(new Uint8Array(hash),b=>b.toString(16).padStart(2,'0')).join('')};}
async function body(request){if(!request.headers.get('content-type')?.includes('application/json'))throw new HttpError(415,'请使用 JSON 提交。');const reader=request.body?.getReader();if(!reader)throw new HttpError(400,'提交内容为空。');let chunks=[],length=0;while(true){const{done,value}=await reader.read();if(done)break;length+=value.length;if(length>16000){await reader.cancel();throw new HttpError(413,'提交内容过长。');}chunks.push(value);}const bytes=new Uint8Array(length);let offset=0;for(const c of chunks){bytes.set(c,offset);offset+=c.length;}try{return JSON.parse(new TextDecoder().decode(bytes));}catch{throw new HttpError(400,'提交格式不正确。');}}
async function handle(request,env,session){
 const url=new URL(request.url),path=url.pathname,db=database(env);
 const propertyResponse=await propertyRoutes(request,db,session,{url,json,rows,text,HttpError,body});if(propertyResponse)return propertyResponse;
 if(request.method==='GET'&&path==='/api/landlords'){const[landlords,reviews]=await Promise.all([allLandlords(db),publicReviews(db)]);return json({landlords:landlords.map(l=>summarize(l,reviews))});}
 if(request.method==='GET'&&path.startsWith('/api/landlords/')){const id=decodeURIComponent(path.slice(15)),landlord=(await allLandlords(db)).find(l=>l.id===id);if(!landlord)throw new HttpError(404,'没有找到这个房东。');let context=null;const listingId=url.searchParams.get('listing');if(listingId){context=await db.prepare('SELECT l.id,l.unit,l.rental_channel,b.address,b.city FROM listings l JOIN buildings b ON l.building_id=b.id WHERE l.id=? AND l.landlord_id=?').bind(listingId,id).first();if(!context)throw new HttpError(404,'没有找到这个 Unit 与房东的对应资料。');}const reviews=(await publicReviews(db)).filter(r=>r.landlord_id===id&&(!listingId||r.listing_id===listingId)).sort((a,b)=>b.created_at-a.created_at);const own=await db.prepare('SELECT status FROM reviews WHERE landlord_id = ? AND session = ? AND scope = ?').bind(id,session.hash,listingId||'').first();return json({landlord:summarize(landlord,reviews),reviews:reviews.map(publicReview),myReviewStatus:own?.status||null,context});}
 if(request.method==='POST'){
  if(request.headers.get('origin')!==url.origin)throw new HttpError(403,'请从本站提交。');const input=await body(request);if(!input||typeof input!=='object'||Array.isArray(input))throw new HttpError(400,'提交格式不正确。');
  if(path==='/api/reviews'){
   const landlordId=text(input.landlordId,1,80,'房东');if(!(await allLandlords(db)).some(l=>l.id===landlordId))throw new HttpError(404,'房东不存在。');
   const listingId=input.listingId||null;if(listingId&&(typeof listingId!=='string'||!(await db.prepare('SELECT id FROM listings WHERE id=? AND landlord_id=?').bind(listingId,landlordId).first())))throw new HttpError(400,'Unit 与房东不匹配。');
   const title=text(input.title,4,80,'标题'),content=text(input.body,20,2000,'评价');for(const key of['maintenance','communication','deposit'])if(!Number.isInteger(input[key])||input[key]<1||input[key]>5)throw new HttpError(400,'请为每个项目选择 1–5 分。');
   if(typeof input.again!=='boolean'||input.consent!==true)throw new HttpError(400,'请确认评价来自你的亲身经历。');if(!Number.isInteger(input.year)||input.year<2000||input.year>new Date().getUTCFullYear())throw new HttpError(400,'请选择有效的租住年份。');
   const count=await db.prepare('SELECT COUNT(*) AS n FROM reviews WHERE session = ? AND created_at > ?').bind(session.hash,Date.now()-86400000).first();if(count.n>=5)throw new HttpError(429,'今天提交的评价较多，请明天再试。');const id=crypto.randomUUID();
   try{await db.prepare('INSERT INTO reviews (id,landlord_id,listing_id,session,scope,maintenance,communication,deposit,again,title,body,year,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,landlordId,listingId,session.hash,listingId||'',input.maintenance,input.communication,input.deposit,Number(input.again),title,content,input.year,'pending',Date.now()).run();}catch(e){if(String(e).includes('UNIQUE'))throw new HttpError(409,'你已为这个房东提交过评价。');throw e;}return json({id,status:'pending',message:'评价已提交，审核通过后会公开展示。'},201);
  }
  if(path==='/api/landlords'){
   const name=text(input.name,2,100,'房东或管理公司名称'),city=text(input.city,2,60,'城市'),district=text(input.district,2,100,'出租楼盘或街区');const count=await db.prepare('SELECT COUNT(*) AS n FROM submissions WHERE session = ? AND created_at > ?').bind(session.hash,Date.now()-86400000).first();if(count.n>=3)throw new HttpError(429,'今天已添加多个房东，请明天再试。');const id=crypto.randomUUID();
   try{await db.batch([db.prepare('INSERT INTO landlords (id,name,city,district,created_at) VALUES (?,?,?,?,?)').bind(id,name,city,district,Date.now()),db.prepare('INSERT INTO submissions (id,session,created_at) VALUES (?,?,?)').bind(crypto.randomUUID(),session.hash,Date.now())]);}catch(e){if(String(e).includes('UNIQUE'))throw new HttpError(409,'这个房东资料已存在，请先搜索。');throw e;}return json({id},201);
  }
  if(path==='/api/reports'){const reviewId=text(input.reviewId,1,80,'评价编号'),reason=text(input.reason,4,500,'举报原因');if(!(await publicReviews(db)).some(r=>r.id===reviewId))throw new HttpError(404,'评价不存在。');try{await db.prepare('INSERT INTO reports (id,review_id,reason,session,created_at) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),reviewId,reason,session.hash,Date.now()).run();}catch(e){if(String(e).includes('UNIQUE'))throw new HttpError(409,'你已举报过这条评价。');throw e;}return json({message:'举报已记录，等待管理员处理。'},201);}
  if(path==='/api/admin/moderate'){if(!env.ADMIN_TOKEN||request.headers.get('authorization')!==`Bearer ${env.ADMIN_TOKEN}`)throw new HttpError(403,'需要管理员权限。');if(!['published','rejected'].includes(input.status))throw new HttpError(400,'无效的审核状态。');const result=await db.prepare('UPDATE reviews SET status = ? WHERE id = ?').bind(input.status,text(input.id,1,80,'评价编号')).run();if(!result.meta.changes)throw new HttpError(404,'评价不存在。');return json({status:input.status});}
 }
 if(request.method==='GET'&&path==='/api/admin/queue'){if(!env.ADMIN_TOKEN||request.headers.get('authorization')!==`Bearer ${env.ADMIN_TOKEN}`)throw new HttpError(403,'需要管理员权限。');return json({reviews:(await rows(db,"SELECT * FROM reviews WHERE status = 'pending' ORDER BY created_at")).map(publicReview),reports:await rows(db,'SELECT id,review_id,reason,created_at FROM reports ORDER BY created_at DESC')});}
 throw new HttpError(404,'页面不存在。');
}
export default{async fetch(request,env){const url=new URL(request.url);if(!url.pathname.startsWith('/api/')){if(!['GET','HEAD'].includes(request.method))return json({error:'不支持此请求。'},405);const asset=assets[url.pathname==='/'?'/index.html':url.pathname];if(!asset)return json({error:'页面不存在。'},404);return new Response(request.method==='HEAD'?null:asset.body,{headers:{...security,'Content-Type':asset.type,'Cache-Control':'no-cache'}});}const session=await identity(request);let response;try{response=await handle(request,env,session);}catch(error){if(!error.status)console.error('Request failed',error);response=json({error:error.status?error.message:'服务暂时不可用，填写的内容仍然保留，请稍后重试。'},error.status||503);}if(session.fresh)response.headers.append('Set-Cookie',`rml_session=${session.id}; HttpOnly; SameSite=Strict; Path=/; Max-Age=31536000${url.protocol==='https:'?'; Secure':''}`);return response;}};
